application:
  order:
    discount:
      percentage:
        enable: false
        threshold: 2
        value: 10
      amount:
        enable: true
        threshold: 2
        value: 10

server:
  port: 8080
  servlet:
    context-path: "/test"